import { Inter } from "next/font/google";
import "./globals.css";
import MainHeader from "@/components/header/MainHeader";
import Providers from "@/lib/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MainHeader />
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
